services:
  unbound:
    build: .
    container_name: unbound-dns
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./unbound/unbound.conf:/usr/local/etc/unbound/unbound.conf:ro
    healthcheck:
      test: ["CMD", "drill", "@10.22.0.253", "google.com"]
      interval: 30s
      timeout: 5s
      retries: 3
